Cart/urls.py
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<id>[\d]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^update-transaction/(?P<id>[-\w]+)/$', update_transaction_records,
        name='update_records')
]

Home/urls.py
from django.conf.urls import url, include
from .views import *
from Products.views import SearchList1

urlpatterns =[
    url(r'^$', home, name='home'),
    url(r'^search1/$', SearchList1.as_view(), name="search1"),
    url(r'^contact/$', contact, name="contact"),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^profile/$', profile, name="profile"),
    url(r'^profile/edit/', editProfile, name="profile_edit"),
    url(r'^profile/delete/(?P<pk>\d+)/$', deleteProfile, name="profile_delete"),
    url(r'^help/', help, name='help'),
    url(r'^products/', include('Products.urls')),
    url(r'^feedback/', Feedback, name='feedback'),
    url(r'^cart/', include('Cart.urls', namespace="cart")),
    url(r'^how-it-work/', Howitworks, name='how_it_work'),
    url(r'^about-us/', aboutus, name='about_us'),
    url(r'^location/', location, name='location'),
    url(r'^location/', location, name='location'),

]

kleider/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^kleider/', include('Home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL   , document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/models.py
from django.db import models
import os
import random
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db.models.signals import post_save
from django.dispatch import receiver



# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    content = models.TextField(default='')

    class Meta:
        db_table = 'contact'

    def __str__(self):
        return self.name


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance, filename):
    new_filename = random.randint(1, 1000)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "users/{final_filename}".format(final_filename=final_filename)


class Profile(models.Model):
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Enter valid phone number. Phone number must be enterd in the formate : '+9999999999'.")
    GANDER_CHOICES= {
        ('M','Male',),
        ('F', 'Female',),
        ('O', 'other',),
    }

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    tel = models.CharField(validators=[phone_regex],max_length=15,blank=True)
    gender = models.CharField(max_length=1, choices=GANDER_CHOICES,)
    birth_date = models.DateField(null=True, blank=True)
    img = models.ImageField(upload_to=upload_image_path, null=True, blank=True)

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Help(models.Model):
    write = models.CharField(max_length=200)

    def __str__(self):
        return self.write

class Feedback(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)
    write = models.CharField(max_length=200)

    def __str__(self):
        return self.write

Products/models.py
from django.db import models
from Home.models import Profile
import os
import random
from django.urls import reverse
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill, SmartResize

# Create your models here.

def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance, filename):
    new_filename = random.randint(1, 1000)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "Products/{final_filename}".format(final_filename=final_filename)


class Product(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male',),
        ('F', 'Female'),
    )
    CONDITION_CHOICES = (
        ('used', 'Uerd',),
        ('new', 'New',),
    )
    CATEGORY_CHOICES = (
        ('traditional', 'Traditional',),
        ('formal', 'Formal',),
        ('casual', 'Casual',),
        ('ethnic', 'Ethnic',),
        ('sports', 'Sports',),
        ('western', 'Western',),
        ('t-shirts', 'T-shirts',),
        ('kids', 'Kids',),
        ('jumpsuits', 'Jumpsuits',),
        ('denim', 'Denim',),
        ('winter', 'Winter war',),
    )
    OCCASION_CHOICES = (
        ('wedding', 'Wedding',),
        ('sangeet', 'Sangeet',),
        ('party', 'Party',),
        ('everyday', 'Everyday',),
        ('interview', 'Interview',),
        ('gym', 'Gym',),
        ('outings', 'Outings',),
    )
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2, default=99.99)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    condition = models.CharField(max_length=4, choices=CONDITION_CHOICES)
    category = models.CharField(max_length=11, choices=CATEGORY_CHOICES)
    occasion = models.CharField(max_length=9, choices=OCCASION_CHOICES)
    featured = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    sold = models.BooleanField(default=False)
    image1 = models.ImageField(upload_to=upload_image_path)
    image2 = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    image3 = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    image4 = models.ImageField(upload_to=upload_image_path, null=True, blank=True)

    smart1 = ImageSpecField(source='image1', processors=[ResizeToFill(250,250)], format="JPEG", options={'quality': 99})
    smart2 = ImageSpecField(source='image2', processors=[SmartResize(250, 250)], format="JPEG", options={'quality': 99})
    smart3 = ImageSpecField(source='image3', processors=[SmartResize(250, 250)], format="JPEG", options={'quality': 99})
    smart4 = ImageSpecField(source='image4', processors=[SmartResize(250, 250)], format="JPEG", options={'quality': 99})

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'Product'

    # on submit click on the product entry page, it redirects to the url below.

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})

templates/aboutus.html
{% load static %}
{% include 'common/header.html' %}

	<!-- breadcrumbs -->
	<div class="w3layouts-breadcrumbs text-center">
		<div class="container">
			<span class="agile-breadcrumbs"><a href="{% url 'home' %}"><i class="fa fa-home home_1"></i></a> / <span>About Us</span></span>
		</div>
	</div>
	<!-- //breadcrumbs -->
	<!---728x90--->




    <center>
    <div style="width: 65%;border: 2px solid #979797;margin-top: 30px;">
        <div style="margin-top: 20px;"></div>
        <h1 style="color: #ff4c4c"><center>About Us</center></h1>
        <hr />
        <div style="margin: 30px;font-size: 16px;">
            We believe fashion is for everyone. And don’t let your wallet tell you any different. Founded in 2017, Alaya by Stage3 was conceptualized to bring a simple vision to life; make runway-ready styles available to you at the click of a button.
        </div>
        <div style="margin: 30px;font-size: 16px;">
            With a finger on the pulse of the latest trends, we asked your favourite celebrity stylists, bloggers, and influencers, to handpick and curate timeless classics for that envious Instagram feed. Dreading the wedding? Stay-cation on the cards? Or is it just the mid-week blues? Look no further. With a wide selection of ethnic and contemporary classics, consider this your one-stop shop for all occasions.
        </div>
        <div style="margin: 30px;font-size: 16px;">
            We like to keep it: Elegant, Effortless and Edgy. And did we mention, Easy! Give your sedentary staples a prim revival and have them delivered straight to your doorstep. Didn’t you hear, convenient is the new chic?
        </div>
        <div style="margin-top: 20px;"></div>
    </div>
    </center>



{% include 'common/footer.html' %}

templates/delete.html
{% load static %}
{% include 'common/header.html' %}


<section>
    <div id="agileits-sign-in-page" class="sign-in-wrapper">
        <div class="agileinfo_signin">
            <form method="post">{% csrf_token %}
                <h3 class="confirm_logout_info">Are you sure Want to delete "{{ object }}" ?</h3>
                <input type="submit" value="Submit" />
            </form>
        </div>
    </div>
</section>

{% include 'common/footer.html' %}

templates/feedback.html
{%load static %}
{% include 'common/header.html' %}
 	<!-- breadcrumbs -->
	<div class="w3layouts-breadcrumbs text-center">
		<div class="container">
			<span class="agile-breadcrumbs"><a href='{% url "home" %}'><i class="fa fa-home home_1"></i></a> / <span>Help</span></span>
		</div>
	</div>
	<!-- //breadcrumbs -->
	<!---728x90--->
{% if messages %}
    <ul class="messages">
		{% for message in messages %}
		    <div class="alert alert-{{ message.tags}} alert-dismissable" role = "alert">
				<button type = "button" class="close" data-dismiss="alert" aria-label="Close">
				   <span aria-hidden="true">&times;</span>
			    </button>
                 {{ message }}
		    </div>
	    {% endfor %}
	</ul>
{% endif %}

	<!-- Faq -->
	<div class="faq main-grid-border">
		<div class="container">
			<div class="wthree-help">
				<h3>write your things</h3>
				<form action="{% url 'feedback' %}" method="post"> {% csrf_token %}
					{{ form.write }}
					<input type="submit" value="submit">
				</form>


			</div>
			<!---728x90--->

templates/list.html
{% load static %}
{% load imagekit %}
{% include 'common/header.html' %}
<!-- switcher-grid and list alignment -->
<script src='{% static "js/tabs.js" %}'></script>
<script type="text/javascript">
$(document).ready(function () {
    var elem=$('#container ul');
	$('#viewcontrols a').on('click',function(e) {
		if ($(this).hasClass('gridview')) {
			elem.fadeOut(1000, function () {
				$('#container ul').removeClass('list').addClass('grid');
				$('#viewcontrols').removeClass('view-controls-list').addClass('view-controls-grid');
				$('#viewcontrols .gridview').addClass('active');
				$('#viewcontrols .listview').removeClass('active');
				elem.fadeIn(1000);
			});
		}
		else if($(this).hasClass('listview')) {
			elem.fadeOut(1000, function () {
				$('#container ul').removeClass('grid').addClass('list');
				$('#viewcontrols').removeClass('view-controls-grid').addClass('view-controls-list');
				$('#viewcontrols .gridview').removeClass('active');
				$('#viewcontrols .listview').addClass('active');
				elem.fadeIn(1000);
			});
		}
	});
});
</script>
<!-- //switcher-grid and list alignment -->
<script>
(function(){
	if(typeof _bsa !== 'undefined' && _bsa) {
  		// format, zoneKey, segment:value, options
  		_bsa.init('flexbar', 'CKYI627U', 'placement:w3layoutscom');
  	}
})();
</script>
<script>
(function(){
if(typeof _bsa !== 'undefined' && _bsa) {
	// format, zoneKey, segment:value, options
	_bsa.init('fancybar', 'CKYDL2JN', 'placement:demo');
}
})();
</script>
<script>
(function(){
	if(typeof _bsa !== 'undefined' && _bsa) {
  		// format, zoneKey, segment:value, options
  		_bsa.init('stickybox', 'CKYI653J', 'placement:w3layoutscom');
  	}
})();
</script><script>
	(function(v,d,o,ai){ai=d.createElement("script");ai.defer=true;ai.async=true;ai.src=v.location.protocol+o;d.head.appendChild(ai);})(window, document, "../../../../../../vdo.ai/core/w3layouts/vdo.ai.js");
	</script><!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-125810435-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-125810435-1');
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','../../../../../../www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-30027142-1', 'w3layouts.com');
  ga('send', 'pageview');
</script>
	<!-- breadcrumbs -->
	<div class="w3layouts-breadcrumbs text-center">
		<div class="container">
			<span class="agile-breadcrumbs"><a href="{% url 'home' %}">
                <i class="fa fa-home home_1"></i></a> / <span>All Ads</span>
            </span>
		</div>
	</div>
	<!-- //breadcrumbs -->
	<!---728x90--->

	<!-- Products -->
	<div class="total-ads main-grid-border">
		<div class="container">
			<div class="ads-grid">
				<div class="side-bar col-md-3">
					<div class="search-hotel">
					<h3 class="agileits-sear-head">Name contains</h3>
					<form method="get" action="{% url 'search' %}">
						<input type="text" name="product" value="Product Name or Category..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Product name...';}" required="">
						<input type="submit" value=" ">
					</form>
				</div>

				<div class="range">
					<h3 class="agileits-sear-head">Price range</h3>
							<ul class="dropdown-menu6">
								<li>
									<div id="slider-range"></div>
                                    <input type="text" id="amount" style="border: 0; color: #ffffff; font-weight: normal;" />
                                </li>
							</ul>
							<!---->
							<script type="text/javascript" src='{% static "js/jquery-ui.js" %}'></script>
							<script type='text/javascript'>//<![CDATA[
							$(window).load(function(){
							 $( "#slider-range" ).slider({
										range: true,
										min: 0,
										max: 9000,
										values: [ 50, 6000 ],
										slide: function( event, ui ) {  $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
										}
							 });
							$( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) + " - $" + $( "#slider-range" ).slider( "values", 1 ) );

							});//]]>

							</script>

				</div>
                </div>
				<div class="agileinfo-ads-display col-md-9">
					<div class="wrapper">
					<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
					  <ul id="myTab" class="nav nav-tabs nav-tabs-responsive" role="tablist">
						<li role="presentation" class="active">
						  <a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">
							<span class="text">All Ads</span>
						  </a>
						</li>
					  </ul>
					  <div id="myTabContent" class="tab-content">
						<div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
						   <div>
                               <div class="container">
								<div class="sort">
								   <div class="sort-by">
										<label>Sort By : </label>
                                        <form method="post" action="{% url 'products' %}">
                                            <select name="sort">
                                                <option value="recent" selected="selected">Most recent</option>
                                                <option value="low">Price: Rs. Low to High</option>
                                                <option value="high">Price: Rs. High to Low</option>
										    </select>
                                            <input type="submit" value=" ">
                                        </form>
									   </div><br/>
									 </div>
								<div class="clearfix"></div>
							<ul class="list">
								{% if object_list %}
								  {% for product in object_list %}
								    <a href="{{ product.get_absolute_url }}">
                                        <li>
										<section class="list-left">
                                        <img src='{{ product.smart1.url }}' title="" alt="" />
                                        <h5 class="title">{{ product.title }}</h5>
                                        <span class="adprice">Rs. {{ product.price }}</span>
                                        <p class="catpath">{{ product.get_category_display }} » {{ product.title }}</p>
                                        </section>
                                        <section class="list-right">
                                         <span class="cityname"><strong>For {{ product.get_occasion_display }}</strong></span>
                                         <span class="adprice">{{ product.get_condition_display }}</span>
											{% if product.user == request.user.profile %}
												<a href='{% url "edit" product.id %}'><input type="submit" value="Edit"></a>
												<a href='{% url "delete" product.id %}'><input type="submit" value="Delete"></a>
											{% elif product in current_order_products %}
											<a href="{% url 'cart:order_summary' %}" class="btn btn-warning">Go to Cart</a>
											{% else %}
											<a href="{% url 'cart:add_to_cart' product.id %}" class="btn btn-warning">Add to Cart</a>
                                       	    {% endif %}
                                        </section>
                                        <div class="clearfix"></div>
                                        </li>
                                    </a>
								{% endfor %}
								{% else %}
								<h2> No entries found</h2>
								{% endif %}
                            </ul>
						</div>
							</div>
						</div>
						<div role="tabpanel" class="tab-pane fade" id="profile" aria-labelledby="profile-tab">
						 <div>
                             <div id="container">
								<div class="view-controls-list" id="viewcontrols">
									<label>view :</label>
									<a class="gridview"><i class="glyphicon glyphicon-th"></i></a>
									<a class="listview active"><i class="glyphicon glyphicon-th-list"></i></a>
								</div>
                             </div>
                         </div>
						</div>
                        {% if is_paginated %}
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                {% else %}
                                    <li class="disabled"><span>&laquo;</span></li>
                                {% endif %}
                                {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                    {% else %}
                                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                {% else %}
                                  <li class="disabled"><span>&raquo;</span></li>
                                {% endif %}
                            </ul>
                        {% endif %}


					  </div>
					</div>
				</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!-- // Products -->
		<!-- Navigation-JavaScript -->
			<script src="../static/static/js/classie.js"></script>
			<script src="../static/static/js/main.js"></script>
		<!-- //Navigation-JavaScript -->
		<!-- here stars scrolling icon -->
			<script type="text/javascript">
				$(document).ready(function() {
					/*
						var defaults = {
						containerID: 'toTop', // fading element id
						containerHoverID: 'toTopHover', // fading element hover id
						scrollSpeed: 1200,
						easingType: 'linear'
						};
					*/

					$().UItoTop({ easingType: 'easeOutQuart' });

					});
			</script>
			<!-- start-smoth-scrolling -->
			<script type="text/javascript" src="../static/static/js/move-top.js"></script>
			<script type="text/javascript" src="../static/static/js/easing.js"></script>
			<script type="text/javascript">
				jQuery(document).ready(function($) {
					$(".scroll").click(function(event){
						event.preventDefault();
						$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
					});
				});
			</script>
			<!-- start-smoth-scrolling -->
		<!-- //here ends scrolling icon -->

<!-- Mirrored from p.w3layouts.com/demos/aug-2016/24-08-2016/resale_v2/web/all-classifieds.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 30 Oct 2018 11:02:06 GMT -->
{% include 'common/footer.html' %}

templates/location.html
{% include 'common/header.html' %}
        <div class="map-w3layouts">
			<h3>Location</h3>
            <iframe width="600" height="350" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDfALcCzRFNLCrLS-9RBkOVka4fDUEg984&q=101,1st Floor, Parshwa Tower,, Above Kotak Mahindra Bank, Near Pakwan II, SG Highway, Bodakdev, Ahmedabad, Gujarat 380054" allowfullscreen></iframe>
		</div>

{% include 'common/footer.html' %}

templates/post.html
{% load static %}
{% load crispy_forms_tags %}
{% include 'common/header.html' %}
<!-- breadcrumbs -->
<div class="w3layouts-breadcrumbs text-center">
    <div class="container">
        <span class="agile-breadcrumbs"><a href='{% url 'home' %}'><i class="fa fa-home home_1"></i></a> / <span>Post an Ad</span></span>
    </div>
</div>
<!-- //breadcrumbs -->
<!---728x90--->

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissable" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
    </ul>
{% endif %}

<!-- Submit Ad -->
<div class="submit-ad main-grid-border">
    <div class="container">
        <h2 class="w3-head">Post an Ad</h2>
        <div class="post-ad-form">
            <form method="post" enctype="multipart/form-data"> {% csrf_token %}
                {{ form.title|as_crispy_field }}
                {{ form.description|as_crispy_field }}
                {{ form.price|as_crispy_field }}
                {{ form.gender|as_crispy_field }}
                {{ form.condition|as_crispy_field }}
                {{ form.category|as_crispy_field }}
                {{ form.occasion|as_crispy_field }}
                {{ form.image1|as_crispy_field }}
                {{ form.image2|as_crispy_field }}
                {{ form.image3|as_crispy_field }}
                {{ form.image4|as_crispy_field }}
                <div class="clearfix"></div>
                <p class="post-terms">By clicking <strong>post Button</strong> you accept our <a href="terms.html" target="_blank">Terms of Use </a> and <a href="privacy.html" target="_blank">Privacy Policy</a></p>
                <input type="submit" value="Post">
                <div class="clearfix"></div>
            </form>
        </div>

    </div>
</div>

<!-- // Submit Ad -->
<!---728x90--->
{% include 'common/footer.html' %}

templates/profiledelete.html
{% load static %}
{% include 'common/header.html' %}


<section>
    <div id="agileits-sign-in-page" class="sign-in-wrapper">
        <div class="agileinfo_signin">
            <form method="post">{% csrf_token %}
                <h3 class="confirm_logout_info">Are you sure Want to delete "{{ object }}" ?</h3>
                <input type="submit" value="Submit" />
            </form>
        </div>
    </div>
</section>

{% include 'common/footer.html' %}

templates/single.html
{% load static %}
{% include 'common/header.html' %}
	<!-- breadcrumbs -->
	<div class="w3layouts-breadcrumbs text-center">
		<div class="container">
			<span class="agile-breadcrumbs">
			<a href='{% url "home" %}'><i class="fa fa-home home_1"></i></a>
			<a href="all-classifieds.html">All Ads</a> /
			<a href="cars.html">{{ object.category.title }}</a> /
			<span>{{ object.title }}</span></span>
		</div>
	</div>
	<!-- //breadcrumbs -->
	<!---728x90--->

	<!--single-page-->
	<div class="single-page main-grid-border">
		<div class="container">
			<div class="product-desc">
				<div class="col-md-7 product-view">
                    <h2>{{ object.title }}</h2>
					<p> Ad ID: {{ object.id }}</p>
					<div class="flexslider">
						<ul class="slides">
							<li data-thumb="{{ object.smart1.url }}">
								<img src="{{ object.smart1.url }}" />
							</li>
                            {% if object.image2 %}
							<li data-thumb="{{ object.smart2.url }}">
								<img src="{{ object.smart2.url }}" />
							</li>
                            {% endif %}
                            {% if object.image3 %}
							<li data-thumb="{{ object.smart3.url }}">
								<img src="{{ object.smart3.url }}" />
							</li>
                            {% endif %}
                            {% if object.image4 %}
							<li data-thumb="{{ object.smart4.url }}">
								<img src="{{ object.smart4.url }}" />
							</li>
                            {% endif %}
						</ul>
					</div>
					<!-- FlexSlider -->
					  <script defer src='{% static "js/jquery.flexslider.js" %}'></script>

						<script>
					// Can also be used with $(document).ready()
					$(window).load(function() {
					  $('.flexslider').flexslider({
						animation: "slide",
						controlNav: "thumbnails"
					  });
					});
					</script>
					<!-- //FlexSlider -->
					<div class="product-details">
						<h4><span class="w3layouts-agileinfo">Best For </span> : <strong>{{ object.get_occasion_display }}</strong></h4>
						<h4><span class="w3layouts-agileinfo">Suits on </span> : {{ object.get_gender_display }}</h4>
						<h4><span class="w3layouts-agileinfo">Description </span> :<p>{{ object.description }}</p><div class="clearfix"></div></h4>

					</div>
				</div>
				<div class="col-md-5 product-details-grid">
					<div class="item-price">
						<div class="product-price">
							<p class="p-price">Price</p>
							<h3 class="rate">Rs. {{ object.price }}</h3>
							<div class="clearfix"></div>
						</div>
						<div class="condition">
							<p class="p-price">Condition</p>
							<h4>{{ object.get_condition_display }}</h4>
							<div class="clearfix"></div>
						</div>
						<div class="itemtype">
							<p class="p-price">Item Type</p>
							<h4>{{ object.get_category_display }}</h4>
							<div class="clearfix"></div>
						</div>
					</div>
					<div class="interested text-center">
						<h4>Interested in this Ad?<small> Contact the Seller!</small></h4>
						<p>{{ object.user.user }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp<i class="glyphicon glyphicon-earphone"></i>{{ object.user.tel }}</p>
					</div>
				</div>
			<div class="clearfix"></div>
			</div>
		</div>
	</div>

{% include 'common/footer.html' %}